#v1- No memory of previous action, no state variables, no motivation variables
<rule_set> ::= <rule>"#"<rule_set>|<rule>"#"
<rule> ::= <precondition_set>":"<action_set>
<precondition_set> ::= <precondition>";"<precondition_set>|<epsilon>
<behaviour_set> ::= <behaviour>";"<behaviour_set>|<epsilon>
<action_set> ::= <action>";"<action_set>|<action>

<precondition> ::= <precondition_terminal>","<boolean>
<precondition_terminal> ::= "P_ON_SOURCE"|"P_ON_NEST"|"P_HAS_RESOURCE"|"P_ON_SLOPE"|"P_ON_CACHE"|"P_NOTHING_DETECTED"|"P_ROBOT_DETECTED"|"P_RESOURCE_DETECTED"|"P_WALL_DETECTED"

<action> ::= <A_B>
<A_B> ::= <behaviour>","<probability>

<behaviour> ::= "B_FORWARD"|""B_BACKWARD"|"B_LEFT"|"B_RIGHT"|"B_DROP"|"B_PICKUP"
<boolean> ::= "true"|"false"
<probability> ::= GE_RANGE:101
<epsilon> ::= "*"
