#!/bin/env bash
#SBATCH --job-name=rwg
#SBATCH --time=24:00:00
#SBATCH --array=1-6
#SBATCH --output=rwg.out
#SBATCH --open-mode=append
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --mail-user=mostafa.rizk@monash.edu

export OMP_NUM_THREADS=1
source /home/mriz9/om18/latest_code/TS-Platform/src/env/bin/activate
CMD=`head -n ${SLURM_ARRAY_TASK_ID} LIST_rwg | tail -1`
$CMD
